# Generated by Django 5.2.7 on 2025-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('C', 'Completed'), ('P', 'Pending')], default='P', max_length=1)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
