# Generated by Django 5.2.7 on 2025-11-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-published']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'In process')], default='P', max_length=1),
        ),
    ]
